package protocols

// ProtocolID is the registry key and the per-protocol stats label
// ("http","ssh","dns","stream"). Never derived from untrusted input.
type ProtocolID string

// ActionKind names a verb within a protocol's action vocabulary
// ("request","fetch-page","connect","run","query","pull-segment", …).
type ActionKind string

// SessionID identifies one virtual user (vuser). It is generated by
// internal/idgen using crypto/rand ONLY — never math/rand (AGENTS.md §2.2).
type SessionID string

// NavID groups the sub-resources of one page-load (or one logical DNS
// resolution) into a single logical unit. "" means "not applicable".
type NavID string

// Canonical ProtocolID values. These four identifiers are the complete,
// authoritative allowlist of protocols PhantomTraffic supports. ProtocolID is
// never derived from untrusted input, but membership is still checked
// fail-closed via IsKnownProtocol so a typo or unsupported value is rejected.
const (
	ProtoHTTP   ProtocolID = "http"
	ProtoDNS    ProtocolID = "dns"
	ProtoSSH    ProtocolID = "ssh"
	ProtoStream ProtocolID = "stream"
)

// knownProtocols is the single source of truth for the supported-protocol
// allowlist. It is unexported and never mutated after package init, so callers
// cannot tamper with the set; they observe it only through IsKnownProtocol and
// KnownProtocols.
var knownProtocols = map[ProtocolID]struct{}{
	ProtoHTTP:   {},
	ProtoDNS:    {},
	ProtoSSH:    {},
	ProtoStream: {},
}

// IsKnownProtocol reports whether p is one of the four supported protocols.
// The match is exact and case-sensitive (an empty string or "HTTP" is not
// known). This is the only membership test callers should use.
func IsKnownProtocol(p ProtocolID) bool {
	_, ok := knownProtocols[p]
	return ok
}

// KnownProtocols returns the four supported protocols in a stable sorted order
// (dns, http, ssh, stream). It allocates a fresh slice on every call so that a
// caller mutating the result cannot affect package state or any other caller;
// the order is fixed (not derived from map iteration) so output is
// deterministic for tests, logs, and help text.
func KnownProtocols() []ProtocolID {
	return []ProtocolID{ProtoDNS, ProtoHTTP, ProtoSSH, ProtoStream}
}
