package protocols

// ProtocolID is the registry key and the per-protocol stats label
// ("http","ssh","dns","stream"). Never derived from untrusted input.
type ProtocolID string

// ActionKind names a verb within a protocol's action vocabulary
// ("request","fetch-page","connect","run","query","pull-segment", …).
type ActionKind string

// SessionID identifies one virtual user (vuser). It is generated by
// internal/idgen using crypto/rand ONLY — never math/rand (AGENTS.md §2.2).
type SessionID string

// NavID groups the sub-resources of one page-load (or one logical DNS
// resolution) into a single logical unit. "" means "not applicable".
type NavID string
